# Test exception

{% embed include file="src/examples/mocking-functions/exception_snippet.t" %}

```
1..2
ok 1
Something went wrong at exception.t line 25.
# Looks like you planned 2 tests but ran 1.
# Looks like your test exited with 255 just after 1.
```



