# Generators - call next

We can also use a `for` loop on the `generator` and then we don't need to worry about the exception.

{% embed include file="src/examples/generators/simple_generator_next_other.py" %}

**Output:**

{% embed include file="src/examples/generators/simple_generator_next_other.out" %}



