
# Yes, this bug is here intentionally
def add(a, b):
    return a * b


