# Exit and finally


* finally


The "finally" part will be called even if we call "return" or "exit" in the "try" block.


{% embed include file="src/examples/exceptions/exit_finally.py" %}




